import { AuditLog } from '../types';

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-1',
    timestamp: '2026-08-05T09:00:00Z',
    userId: 'usr-vendor',
    userName: 'Amit Patel',
    userRole: 'VENDOR',
    action: 'REGISTERED_VENDOR',
    entity: 'VENDOR',
    entityId: 'ven-1',
    description: 'Submitted onboarding registration and 4 mandatory tax/statutory documents.',
    ipAddress: '49.207.180.12',
  },
  {
    id: 'aud-2',
    timestamp: '2026-08-10T10:30:00Z',
    userId: 'usr-procurement',
    userName: 'Rohan Mehta',
    userRole: 'PROCUREMENT',
    action: 'VERIFIED_VENDOR',
    entity: 'VENDOR',
    entityId: 'ven-1',
    description: 'Completed statutory document verification (GST, PAN, Incorporation, Bank proof).',
    ipAddress: '192.168.1.45',
  },
  {
    id: 'aud-3',
    timestamp: '2026-08-11T14:15:00Z',
    userId: 'usr-admin',
    userName: 'Rajesh Verma',
    userRole: 'ADMIN',
    action: 'APPROVED_VENDOR',
    entity: 'VENDOR',
    entityId: 'ven-1',
    description: 'Granted final administrative onboarding approval. Vendor status set to ACTIVE.',
    ipAddress: '192.168.1.10',
  },
  {
    id: 'aud-4',
    timestamp: '2026-08-25T16:00:00Z',
    userId: 'usr-admin',
    userName: 'Rajesh Verma',
    userRole: 'ADMIN',
    action: 'REJECTED_VENDOR',
    entity: 'VENDOR',
    entityId: 'ven-5',
    description: 'Rejected onboarding: Invalid GST identification number and expired trade compliance.',
    ipAddress: '192.168.1.10',
  },
  {
    id: 'aud-5',
    timestamp: '2026-09-01T09:00:00Z',
    userId: 'usr-finance',
    userName: 'Ananya Sharma',
    userRole: 'FINANCE',
    action: 'CREATED_PURCHASE_REQUEST',
    entity: 'PURCHASE_REQUEST',
    entityId: 'pr-4',
    description: 'Created PR-2026-004 for Backup Storage Node with total value ₹1,50,000.',
    ipAddress: '192.168.1.52',
  },
  {
    id: 'aud-6',
    timestamp: '2026-09-02T10:00:00Z',
    userId: 'usr-finance',
    userName: 'Ananya Sharma',
    userRole: 'FINANCE',
    action: 'APPROVED_PURCHASE_REQUEST',
    entity: 'PURCHASE_REQUEST',
    entityId: 'pr-4',
    description: 'Level 1 Department signoff recorded for PR-2026-004.',
    ipAddress: '192.168.1.52',
  },
  {
    id: 'aud-7',
    timestamp: '2026-09-03T11:30:00Z',
    userId: 'usr-proc-mgr',
    userName: 'Sunita Krishnan',
    userRole: 'PROCUREMENT_MANAGER',
    action: 'APPROVED_PURCHASE_REQUEST',
    entity: 'PURCHASE_REQUEST',
    entityId: 'pr-4',
    description: 'Level 2 Procurement Manager signoff recorded for PR-2026-004.',
    ipAddress: '192.168.1.33',
  },
  {
    id: 'aud-8',
    timestamp: '2026-09-04T16:00:00Z',
    userId: 'usr-finance',
    userName: 'Ananya Sharma',
    userRole: 'FINANCE',
    action: 'APPROVED_PURCHASE_REQUEST',
    entity: 'PURCHASE_REQUEST',
    entityId: 'pr-4',
    description: 'Level 3 Finance Controller final signoff recorded. PR status updated to APPROVED.',
    ipAddress: '192.168.1.52',
  },
  {
    id: 'aud-9',
    timestamp: '2026-09-05T09:30:00Z',
    userId: 'usr-procurement',
    userName: 'Rohan Mehta',
    userRole: 'PROCUREMENT',
    action: 'CREATED_RFQ',
    entity: 'RFQ',
    entityId: 'rfq-2',
    description: 'Published RFQ-2026-002 linked to PR-2026-004; dispatched invitations to eligible vendors.',
    ipAddress: '192.168.1.45',
  },
  {
    id: 'aud-10',
    timestamp: '2026-09-07T12:00:00Z',
    userId: 'usr-vendor',
    userName: 'Suresh Raina',
    userRole: 'VENDOR',
    action: 'SUBMITTED_QUOTATION',
    entity: 'QUOTATION',
    entityId: 'quo-4',
    description: 'Submitted formal commercial quotation QUO-2026-004 (₹1,48,680) for RFQ-2026-002.',
    ipAddress: '103.21.124.9',
  },
  {
    id: 'aud-11',
    timestamp: '2026-09-09T14:00:00Z',
    userId: 'usr-procurement',
    userName: 'Rohan Mehta',
    userRole: 'PROCUREMENT',
    action: 'SELECTED_VENDOR',
    entity: 'QUOTATION',
    entityId: 'quo-4',
    description: 'Quotation comparison evaluated. Awarded bid to CloudPeak Infrastructure Ltd.',
    ipAddress: '192.168.1.45',
  },
  {
    id: 'aud-12',
    timestamp: '2026-09-10T14:00:00Z',
    userId: 'usr-procurement',
    userName: 'Rohan Mehta',
    userRole: 'PROCUREMENT',
    action: 'GENERATED_PURCHASE_ORDER',
    entity: 'PURCHASE_ORDER',
    entityId: 'po-1',
    description: 'Generated PO-2026-0001 for ₹1,48,680 against selected quotation QUO-2026-004.',
    ipAddress: '192.168.1.45',
  },
  {
    id: 'aud-13',
    timestamp: '2026-09-15T10:00:00Z',
    userId: 'usr-manager',
    userName: 'Vikram Malhotra',
    userRole: 'DEPARTMENT_MANAGER',
    action: 'CREATED_PURCHASE_REQUEST',
    entity: 'PURCHASE_REQUEST',
    entityId: 'pr-3',
    description: 'Created PR-2026-003 for Rack Mount Core Switches (₹85,000).',
    ipAddress: '192.168.1.22',
  },
  {
    id: 'aud-14',
    timestamp: '2026-09-17T09:00:00Z',
    userId: 'usr-procurement',
    userName: 'Rohan Mehta',
    userRole: 'PROCUREMENT',
    action: 'CREATED_RFQ',
    entity: 'RFQ',
    entityId: 'rfq-1',
    description: 'Initiated competitive bidding RFQ-2026-001 for Cisco Catalyst Switch.',
    ipAddress: '192.168.1.45',
  },
  {
    id: 'aud-15',
    timestamp: '2026-09-18T14:30:00Z',
    userId: 'usr-vendor',
    userName: 'Karan Singhal',
    userRole: 'VENDOR',
    action: 'REGISTERED_VENDOR',
    entity: 'VENDOR',
    entityId: 'ven-3',
    description: 'Vertex Office Supplies submitted registration dossier.',
    ipAddress: '14.139.24.8',
  },
  {
    id: 'aud-16',
    timestamp: '2026-09-20T16:20:00Z',
    userId: 'usr-procurement',
    userName: 'Rohan Mehta',
    userRole: 'PROCUREMENT',
    action: 'VERIFIED_VENDOR',
    entity: 'VENDOR',
    entityId: 'ven-4',
    description: 'Verified statutory credentials for PrimeLogix Enterprise Solutions; forwarded for Admin signoff.',
    ipAddress: '192.168.1.45',
  },
  {
    id: 'aud-17',
    timestamp: '2026-09-21T10:00:00Z',
    userId: 'usr-manager',
    userName: 'Vikram Malhotra',
    userRole: 'DEPARTMENT_MANAGER',
    action: 'CREATED_PURCHASE_REQUEST',
    entity: 'PURCHASE_REQUEST',
    entityId: 'pr-1',
    description: 'Created PR-2026-001 (₹50,000) for Developer 4K Monitors.',
    ipAddress: '192.168.1.22',
  },
];
