import { Notification } from '../types';

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    targetRole: 'PROCUREMENT',
    title: 'New Vendor Registration',
    message: 'Vertex Office Supplies submitted onboarding documents for verification.',
    type: 'ACTION_REQUIRED',
    link: '/procurement/vendors',
    isRead: false,
    createdAt: '2026-09-18T14:35:00Z',
  },
  {
    id: 'notif-2',
    targetRole: 'ADMIN',
    title: 'Vendor Verification Pending Final Approval',
    message: 'PrimeLogix Enterprise Solutions was verified by Procurement and requires Admin approval.',
    type: 'ACTION_REQUIRED',
    link: '/admin/vendors',
    isRead: false,
    createdAt: '2026-09-20T16:22:00Z',
  },
  {
    id: 'notif-3',
    targetRole: 'DEPARTMENT_MANAGER',
    title: 'Purchase Request Pending Your Review',
    message: 'PR-2026-001 (₹50,000) for Developer Monitors requires your Level 1 approval.',
    type: 'ACTION_REQUIRED',
    link: '/manager/approvals',
    isRead: false,
    createdAt: '2026-09-21T10:05:00Z',
  },
  {
    id: 'notif-4',
    targetRole: 'PROCUREMENT_MANAGER',
    title: 'Purchase Request Approvals Queue',
    message: 'New purchase requests await Level 2 Procurement Manager signoff.',
    type: 'INFO',
    link: '/procurement/approvals',
    isRead: false,
    createdAt: '2026-09-21T10:10:00Z',
  },
  {
    id: 'notif-5',
    targetRole: 'VENDOR',
    title: 'New RFQ Invitation',
    message: 'You have been invited to quote for RFQ-2026-001: Enterprise L3 Core Switches.',
    type: 'INFO',
    link: '/vendor/rfqs',
    isRead: false,
    createdAt: '2026-09-17T09:35:00Z',
  },
  {
    id: 'notif-6',
    targetRole: 'PROCUREMENT',
    title: 'Quotations Received for RFQ-2026-001',
    message: 'Quotations submitted by Techtron Electronics and CloudPeak are ready for comparison.',
    type: 'INFO',
    link: '/procurement/quotations',
    isRead: false,
    createdAt: '2026-09-18T16:00:00Z',
  },
  {
    id: 'notif-7',
    targetRole: 'VENDOR',
    title: 'Quotation Selected & PO Issued',
    message: 'Congratulations! Your quotation for RFQ-2026-002 was selected. PO-2026-0001 has been issued.',
    type: 'SUCCESS',
    link: '/vendor/purchase-orders',
    isRead: true,
    createdAt: '2026-09-10T14:10:00Z',
  },
  {
    id: 'notif-8',
    targetRole: 'FINANCE',
    title: 'Purchase Order Spend Committed',
    message: 'PO-2026-0001 committed ₹1,48,680 against Finance & Accounts backup infrastructure budget.',
    type: 'INFO',
    link: '/finance/spend',
    isRead: true,
    createdAt: '2026-09-10T14:15:00Z',
  },
  {
    id: 'notif-9',
    targetRole: 'AUDITOR',
    title: 'Audit Log Integrity Check Passed',
    message: 'All procurement and approval trail hashes reconciled successfully for current quarter.',
    type: 'INFO',
    link: '/auditor/audit-logs',
    isRead: true,
    createdAt: '2026-09-22T08:00:00Z',
  },
  {
    id: 'notif-10',
    targetRole: 'PROCUREMENT',
    title: 'RFQ Deadline Notice',
    message: 'Submission deadline for RFQ-2026-001 is approaching on 30 Sep 2026.',
    type: 'WARNING',
    link: '/procurement/rfqs',
    isRead: true,
    createdAt: '2026-09-22T09:00:00Z',
  },
];
