import { PurchaseOrder } from '../types';

export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: 'po-1',
    poNumber: 'PO-2026-0001',
    purchaseRequestId: 'pr-4',
    purchaseRequestNumber: 'PR-2026-004',
    rfqId: 'rfq-2',
    rfqNumber: 'RFQ-2026-002',
    quotationId: 'quo-4',
    quotationNumber: 'QUO-2026-004',
    vendorId: 'ven-2',
    vendorName: 'CloudPeak Infrastructure Ltd',
    vendorAddress: 'Floor 8, DLF Cyber City, Tower B, Gurugram, Haryana - 122002',
    vendorGst: '06AABCC5678K1Z2',
    items: [
      {
        id: 'poi-1',
        item: 'Synology RackStation RS3621xs+ & 12x 16TB Enterprise HDDs',
        description: '12-bay NAS Storage with Enterprise HDDs and 5-Year OEM warranty',
        quantity: 1,
        unitPrice: 126000,
        subtotal: 126000,
      },
    ],
    subtotal: 126000,
    taxRate: 18,
    taxAmount: 22680,
    totalAmount: 148680,
    deliveryDate: '2026-10-15',
    deliveryAddress: 'Sourcelyx Technologies Ltd, Cyber Gateway Tower 3, Gurugram, Haryana - 122002',
    paymentTerms: 'Net 45 days after inspection and commissioning',
    createdById: 'usr-procurement',
    createdByName: 'Rohan Mehta',
    orderDate: '2026-09-10',
    status: 'ACKNOWLEDGED',
    notes: 'Please quote PO Number on all shipping notes, bills of lading, and tax invoices.',
  },
  {
    id: 'po-2',
    poNumber: 'PO-2026-0002',
    purchaseRequestId: 'pr-101',
    purchaseRequestNumber: 'PR-2026-098',
    rfqId: 'rfq-101',
    rfqNumber: 'RFQ-2026-088',
    quotationId: 'quo-101',
    quotationNumber: 'QUO-2026-077',
    vendorId: 'ven-1',
    vendorName: 'Techtron Electronics Pvt Ltd',
    vendorAddress: 'Plot 42, Electronic City Phase 1, Bengaluru, Karnataka - 560100',
    vendorGst: '29ABCDE1234F1Z5',
    items: [
      {
        id: 'poi-2',
        item: 'MacBook Pro 16" M3 Pro / 36GB / 512GB SSD',
        description: 'Developer laptops for lead AI engineers',
        quantity: 2,
        unitPrice: 220000,
        subtotal: 440000,
      },
    ],
    subtotal: 440000,
    taxRate: 18,
    taxAmount: 79200,
    totalAmount: 519200,
    deliveryDate: '2026-09-28',
    deliveryAddress: 'Sourcelyx Campus, Tower B, Outer Ring Road, Bengaluru - 560103',
    paymentTerms: 'Net 30 days',
    createdById: 'usr-procurement',
    createdByName: 'Rohan Mehta',
    orderDate: '2026-09-08',
    status: 'SENT',
    notes: 'Warranty documentation to be handed over along with physical devices.',
  },
  {
    id: 'po-3',
    poNumber: 'PO-2026-0003',
    purchaseRequestId: 'pr-102',
    purchaseRequestNumber: 'PR-2026-074',
    rfqId: 'rfq-102',
    rfqNumber: 'RFQ-2026-065',
    quotationId: 'quo-102',
    quotationNumber: 'QUO-2026-052',
    vendorId: 'ven-1',
    vendorName: 'Techtron Electronics Pvt Ltd',
    vendorAddress: 'Plot 42, Electronic City Phase 1, Bengaluru, Karnataka - 560100',
    vendorGst: '29ABCDE1234F1Z5',
    items: [
      {
        id: 'poi-3',
        item: 'UPS Backup Units 2kVA Online',
        description: 'Modular enterprise battery backup unit for testing lab',
        quantity: 2,
        unitPrice: 35000,
        subtotal: 70000,
      },
    ],
    subtotal: 70000,
    taxRate: 18,
    taxAmount: 12600,
    totalAmount: 82600,
    deliveryDate: '2026-09-15',
    deliveryAddress: 'Sourcelyx Campus, Tower B, Outer Ring Road, Bengaluru - 560103',
    paymentTerms: 'Net 30 days',
    createdById: 'usr-procurement',
    createdByName: 'Rohan Mehta',
    orderDate: '2026-08-28',
    status: 'COMPLETED',
    notes: 'Delivery inspected and GRN acknowledged.',
  },
];
