import { PurchaseRequest } from '../types';

export const INITIAL_PURCHASE_REQUESTS: PurchaseRequest[] = [
  {
    id: 'pr-1',
    requestNumber: 'PR-2026-001',
    title: 'High-Performance Developer Monitors & Docks',
    description: 'Procurement of 5x 27-inch 4K USB-C monitors for new senior engineers in the Core Platform team.',
    justification: 'Quarterly hiring onboarding hardware requirements for Q3 engineering sprint.',
    departmentId: 'dept-eng',
    departmentName: 'Engineering',
    requestedById: 'usr-manager',
    requestedByName: 'Vikram Malhotra',
    priority: 'HIGH',
    requiredDate: '2026-10-15',
    items: [
      {
        id: 'pri-1',
        item: 'Dell UltraSharp 27" 4K Monitor',
        description: 'U2723QE with USB-C Hub',
        quantity: 2,
        unitPrice: 25000,
        total: 50000,
      },
    ],
    totalAmount: 50000,
    status: 'PENDING_APPROVAL',
    currentApprovalLevel: 1,
    totalApprovalLevels: 2,
    approvals: [
      {
        level: 1,
        role: 'DEPARTMENT_MANAGER',
        roleName: 'Department Manager',
        status: 'PENDING',
      },
      {
        level: 2,
        role: 'PROCUREMENT_MANAGER',
        roleName: 'Procurement Manager',
        status: 'PENDING',
      },
    ],
    createdAt: '2026-09-21T10:00:00Z',
    updatedAt: '2026-09-21T10:00:00Z',
  },
  {
    id: 'pr-2',
    requestNumber: 'PR-2026-002',
    title: 'Ergonomic Office Peripherals & Accessories',
    description: 'Wireless ergonomic keyboards, vertical mice, and wrist rests for developer workstations.',
    justification: 'Workplace health and ergonomics compliance.',
    departmentId: 'dept-eng',
    departmentName: 'Engineering',
    requestedById: 'usr-manager',
    requestedByName: 'Vikram Malhotra',
    priority: 'MEDIUM',
    requiredDate: '2026-10-05',
    items: [
      {
        id: 'pri-2',
        item: 'Logitech MX Master 3S + Ergo Keyboard Combo',
        description: 'Bluetooth multi-device peripherals',
        quantity: 3,
        unitPrice: 6000,
        total: 18000,
      },
    ],
    totalAmount: 18000,
    status: 'APPROVED',
    currentApprovalLevel: 1,
    totalApprovalLevels: 1,
    approvals: [
      {
        level: 1,
        role: 'DEPARTMENT_MANAGER',
        roleName: 'Department Manager',
        assignedToName: 'Vikram Malhotra',
        status: 'APPROVED',
        actionDate: '2026-09-18T14:00:00Z',
        actionBy: 'Vikram Malhotra',
        comments: 'Approved within department Q3 expense threshold.',
      },
    ],
    createdAt: '2026-09-18T09:30:00Z',
    updatedAt: '2026-09-18T14:00:00Z',
  },
  {
    id: 'pr-3',
    requestNumber: 'PR-2026-003',
    title: 'Rack Mount Core Switch & SFP+ Modules',
    description: 'Enterprise L3 managed network switch with 48x 1GbE and 4x 10G SFP+ uplinks.',
    justification: 'Server room connectivity expansion for testing cluster.',
    departmentId: 'dept-eng',
    departmentName: 'Engineering',
    requestedById: 'usr-manager',
    requestedByName: 'Vikram Malhotra',
    priority: 'URGENT',
    requiredDate: '2026-10-10',
    items: [
      {
        id: 'pri-3',
        item: 'Cisco Catalyst 1000 48-Port Switch',
        description: 'C1000-48T-4G-L Switch with 10G transceivers',
        quantity: 1,
        unitPrice: 85000,
        total: 85000,
      },
    ],
    totalAmount: 85000,
    status: 'RFQ_CREATED',
    currentApprovalLevel: 2,
    totalApprovalLevels: 2,
    approvals: [
      {
        level: 1,
        role: 'DEPARTMENT_MANAGER',
        roleName: 'Department Manager',
        status: 'APPROVED',
        actionDate: '2026-09-15T11:00:00Z',
        actionBy: 'Vikram Malhotra',
        comments: 'Critical network upgrade approved.',
      },
      {
        level: 2,
        role: 'PROCUREMENT_MANAGER',
        roleName: 'Procurement Manager',
        status: 'APPROVED',
        actionDate: '2026-09-16T15:30:00Z',
        actionBy: 'Sunita Krishnan',
        comments: 'Procurement budget allocated. Proceed with RFQ.',
      },
    ],
    rfqId: 'rfq-1',
    createdAt: '2026-09-15T10:00:00Z',
    updatedAt: '2026-09-17T09:00:00Z',
  },
  {
    id: 'pr-4',
    requestNumber: 'PR-2026-004',
    title: 'Enterprise Cloud Backup Storage Appliances',
    description: 'High-density backup storage node for disaster recovery site.',
    justification: 'Statutory compliance and financial audit disaster recovery SLA requirement.',
    departmentId: 'dept-fin',
    departmentName: 'Finance & Accounts',
    requestedById: 'usr-finance',
    requestedByName: 'Ananya Sharma',
    priority: 'HIGH',
    requiredDate: '2026-10-20',
    items: [
      {
        id: 'pri-4',
        item: 'Synology RackStation RS3621xs+',
        description: '12-bay NAS Storage with Enterprise HDDs',
        quantity: 1,
        unitPrice: 150000,
        total: 150000,
      },
    ],
    totalAmount: 150000,
    status: 'PO_GENERATED',
    currentApprovalLevel: 3,
    totalApprovalLevels: 3,
    approvals: [
      {
        level: 1,
        role: 'DEPARTMENT_MANAGER',
        roleName: 'Department Manager',
        status: 'APPROVED',
        actionDate: '2026-09-02T10:00:00Z',
        actionBy: 'Ananya Sharma',
      },
      {
        level: 2,
        role: 'PROCUREMENT_MANAGER',
        roleName: 'Procurement Manager',
        status: 'APPROVED',
        actionDate: '2026-09-03T11:30:00Z',
        actionBy: 'Sunita Krishnan',
      },
      {
        level: 3,
        role: 'FINANCE',
        roleName: 'Finance Controller',
        status: 'APPROVED',
        actionDate: '2026-09-04T16:00:00Z',
        actionBy: 'Ananya Sharma',
      },
    ],
    rfqId: 'rfq-2',
    poId: 'po-1',
    createdAt: '2026-09-01T09:00:00Z',
    updatedAt: '2026-09-10T14:00:00Z',
  },
  {
    id: 'pr-5',
    requestNumber: 'PR-2026-005',
    title: 'Recruitment Portal Subscription & Assessment Tokens',
    description: 'Technical assessment platform tokens for campus hiring drive.',
    justification: 'Quarterly hiring drive candidate screening.',
    departmentId: 'dept-hr',
    departmentName: 'Human Resources',
    requestedById: 'usr-hr-mgr',
    requestedByName: 'Priya Nambiar',
    priority: 'LOW',
    requiredDate: '2026-10-30',
    items: [
      {
        id: 'pri-5',
        item: 'Assessment Platform Tier 2 Tokens',
        description: 'Pack of 500 coding test tokens',
        quantity: 1,
        unitPrice: 12000,
        total: 12000,
      },
    ],
    totalAmount: 12000,
    status: 'DRAFT',
    currentApprovalLevel: 1,
    totalApprovalLevels: 1,
    approvals: [
      {
        level: 1,
        role: 'DEPARTMENT_MANAGER',
        roleName: 'Department Manager',
        status: 'PENDING',
      },
    ],
    createdAt: '2026-09-22T11:00:00Z',
    updatedAt: '2026-09-22T11:00:00Z',
  },
];
