import { RFQ } from '../types';

export const INITIAL_RFQS: RFQ[] = [
  {
    id: 'rfq-1',
    rfqNumber: 'RFQ-2026-001',
    title: 'Procurement of Enterprise L3 Managed Core Switches',
    description: 'Bids invited for supplying Cisco Catalyst 1000 48-Port Switch or equivalent L3 enterprise switch with SFP+ 10G transceiver modules.',
    purchaseRequestId: 'pr-3',
    purchaseRequestNumber: 'PR-2026-003',
    deadline: '2026-09-30',
    deliveryRequirements: 'Delivery to Bengaluru DC within 14 calendar days from PO date.',
    paymentTerms: 'Net 30 days upon delivery and physical acceptance.',
    status: 'OPEN',
    invitedVendors: [
      {
        vendorId: 'ven-1',
        vendorName: 'Techtron Electronics Pvt Ltd',
        contactEmail: 'vendor@sourcelyx.com',
        invitedAt: '2026-09-17T09:30:00Z',
        hasQuoted: true,
      },
      {
        vendorId: 'ven-2',
        vendorName: 'CloudPeak Infrastructure Ltd',
        contactEmail: 'suresh@cloudpeak.in',
        invitedAt: '2026-09-17T09:30:00Z',
        hasQuoted: true,
      },
    ],
    quotationCount: 2,
    createdAt: '2026-09-17T09:00:00Z',
    createdBy: 'Rohan Mehta',
  },
  {
    id: 'rfq-2',
    rfqNumber: 'RFQ-2026-002',
    title: 'Enterprise High-Density Backup Storage Node',
    description: 'Hardware bid for Synology RS3621xs+ with 12x 16TB Enterprise SATA HDDs and 5-year on-site NBD warranty support.',
    purchaseRequestId: 'pr-4',
    purchaseRequestNumber: 'PR-2026-004',
    deadline: '2026-09-10',
    deliveryRequirements: 'Delivery and rack installation in Gurugram Datacenter.',
    paymentTerms: 'Net 45 days after inspection and commissioning.',
    status: 'AWARDED',
    invitedVendors: [
      {
        vendorId: 'ven-1',
        vendorName: 'Techtron Electronics Pvt Ltd',
        contactEmail: 'vendor@sourcelyx.com',
        invitedAt: '2026-09-05T10:00:00Z',
        hasQuoted: true,
      },
      {
        vendorId: 'ven-2',
        vendorName: 'CloudPeak Infrastructure Ltd',
        contactEmail: 'suresh@cloudpeak.in',
        invitedAt: '2026-09-05T10:00:00Z',
        hasQuoted: true,
      },
    ],
    quotationCount: 2,
    createdAt: '2026-09-05T09:30:00Z',
    createdBy: 'Rohan Mehta',
  },
  {
    id: 'rfq-3',
    rfqNumber: 'RFQ-2026-003',
    title: 'Ergonomic Developer Workstation Peripherals',
    description: 'Commercial supplies of ergonomic keyboards, mice and wrist supports for Bangalore software engineering teams.',
    purchaseRequestId: 'pr-2',
    purchaseRequestNumber: 'PR-2026-002',
    deadline: '2026-10-02',
    deliveryRequirements: 'Bengaluru Tech Park campus reception.',
    paymentTerms: 'Net 15 days upon receipt.',
    status: 'OPEN',
    invitedVendors: [
      {
        vendorId: 'ven-1',
        vendorName: 'Techtron Electronics Pvt Ltd',
        contactEmail: 'vendor@sourcelyx.com',
        invitedAt: '2026-09-19T10:00:00Z',
        hasQuoted: false,
      },
    ],
    quotationCount: 0,
    createdAt: '2026-09-19T09:00:00Z',
    createdBy: 'Rohan Mehta',
  },
];
