import { Vendor } from '../types';

export const INITIAL_VENDORS: Vendor[] = [
  {
    id: 'ven-1',
    companyName: 'Techtron Electronics Pvt Ltd',
    businessType: 'Private Limited',
    contactPerson: 'Amit Patel',
    email: 'vendor@sourcelyx.com',
    phone: '+91 98201 12345',
    address: 'Plot 42, Electronic City Phase 1',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560100',
    gstNumber: '29ABCDE1234F1Z5',
    panNumber: 'ABCDE1234F',
    bankName: 'HDFC Bank',
    bankAccount: '50200012345678',
    ifscCode: 'HDFC0000123',
    status: 'ACTIVE',
    verifiedAt: '2026-08-10T10:30:00Z',
    verifiedBy: 'Rohan Mehta',
    approvedAt: '2026-08-11T14:15:00Z',
    approvedBy: 'Rajesh Verma',
    createdAt: '2026-08-05T09:00:00Z',
    category: 'IT Hardware & Systems',
    documents: [
      {
        id: 'doc-1',
        name: 'Techtron_GST_Certificate.pdf',
        type: 'GST_CERTIFICATE',
        url: '#',
        fileSize: '1.2 MB',
        uploadedAt: '2026-08-05T09:00:00Z',
        verified: true,
      },
      {
        id: 'doc-2',
        name: 'Techtron_PAN_Card.pdf',
        type: 'PAN',
        url: '#',
        fileSize: '450 KB',
        uploadedAt: '2026-08-05T09:00:00Z',
        verified: true,
      },
      {
        id: 'doc-3',
        name: 'Incorporation_Cert_Techtron.pdf',
        type: 'BUSINESS_REG',
        url: '#',
        fileSize: '2.1 MB',
        uploadedAt: '2026-08-05T09:00:00Z',
        verified: true,
      },
      {
        id: 'doc-4',
        name: 'Cancelled_Cheque_HDFC.pdf',
        type: 'BANK_PROOF',
        url: '#',
        fileSize: '680 KB',
        uploadedAt: '2026-08-05T09:00:00Z',
        verified: true,
      },
    ],
    performance: {
      deliveryPerformance: 96,
      qualityRating: 4.8,
      priceCompetitiveness: 4.6,
      responseRate: 98,
      overallRating: 4.8,
      totalOrdersCompleted: 24,
    },
  },
  {
    id: 'ven-2',
    companyName: 'CloudPeak Infrastructure Ltd',
    businessType: 'Public Limited',
    contactPerson: 'Suresh Raina',
    email: 'suresh@cloudpeak.in',
    phone: '+91 99302 67890',
    address: 'Floor 8, DLF Cyber City, Tower B',
    city: 'Gurugram',
    state: 'Haryana',
    pincode: '122002',
    gstNumber: '06AABCC5678K1Z2',
    panNumber: 'AABCC5678K',
    bankName: 'ICICI Bank',
    bankAccount: '001105012398',
    ifscCode: 'ICIC0000011',
    status: 'ACTIVE',
    verifiedAt: '2026-08-15T11:00:00Z',
    verifiedBy: 'Rohan Mehta',
    approvedAt: '2026-08-16T16:00:00Z',
    approvedBy: 'Rajesh Verma',
    createdAt: '2026-08-12T10:00:00Z',
    category: 'Cloud & SaaS Solutions',
    documents: [
      {
        id: 'doc-21',
        name: 'CloudPeak_GST_Reg.pdf',
        type: 'GST_CERTIFICATE',
        url: '#',
        fileSize: '1.4 MB',
        uploadedAt: '2026-08-12T10:00:00Z',
        verified: true,
      },
      {
        id: 'doc-22',
        name: 'PAN_CloudPeak.pdf',
        type: 'PAN',
        url: '#',
        fileSize: '512 KB',
        uploadedAt: '2026-08-12T10:00:00Z',
        verified: true,
      },
      {
        id: 'doc-23',
        name: 'Bank_Statement_Verified.pdf',
        type: 'BANK_PROOF',
        url: '#',
        fileSize: '1.8 MB',
        uploadedAt: '2026-08-12T10:00:00Z',
        verified: true,
      },
    ],
    performance: {
      deliveryPerformance: 92,
      qualityRating: 4.5,
      priceCompetitiveness: 4.4,
      responseRate: 94,
      overallRating: 4.5,
      totalOrdersCompleted: 15,
    },
  },
  {
    id: 'ven-3',
    companyName: 'Vertex Office Supplies',
    businessType: 'Partnership',
    contactPerson: 'Karan Singhal',
    email: 'contact@vertexsupplies.com',
    phone: '+91 97110 54321',
    address: '14, Industrial Area, Okhla Phase 2',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110020',
    gstNumber: '07AAAFV4321Q1Z8',
    panNumber: 'AAAFV4321Q',
    bankName: 'State Bank of India',
    bankAccount: '33445566778',
    ifscCode: 'SBIN0001234',
    status: 'PENDING_VERIFICATION',
    createdAt: '2026-09-18T14:30:00Z',
    category: 'Office Automation & Supplies',
    documents: [
      {
        id: 'doc-31',
        name: 'GST_Registration_Vertex.pdf',
        type: 'GST_CERTIFICATE',
        url: '#',
        fileSize: '950 KB',
        uploadedAt: '2026-09-18T14:30:00Z',
        verified: false,
      },
      {
        id: 'doc-32',
        name: 'PAN_Card_Vertex.pdf',
        type: 'PAN',
        url: '#',
        fileSize: '390 KB',
        uploadedAt: '2026-09-18T14:30:00Z',
        verified: false,
      },
      {
        id: 'doc-33',
        name: 'Partnership_Deed.pdf',
        type: 'BUSINESS_REG',
        url: '#',
        fileSize: '3.4 MB',
        uploadedAt: '2026-09-18T14:30:00Z',
        verified: false,
      },
    ],
    performance: {
      deliveryPerformance: 88,
      qualityRating: 4.1,
      priceCompetitiveness: 4.7,
      responseRate: 90,
      overallRating: 4.2,
      totalOrdersCompleted: 8,
    },
  },
  {
    id: 'ven-4',
    companyName: 'PrimeLogix Enterprise Solutions',
    businessType: 'Private Limited',
    contactPerson: 'Deepa Roy',
    email: 'deepa@primelogix.io',
    phone: '+91 98450 99887',
    address: '77, Outer Ring Road, Bellandur',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560103',
    gstNumber: '29AAGCP9876R1Z9',
    panNumber: 'AAGCP9876R',
    bankName: 'Axis Bank',
    bankAccount: '918020034455667',
    ifscCode: 'UTIB0000456',
    status: 'PENDING_APPROVAL',
    verifiedAt: '2026-09-20T16:20:00Z',
    verifiedBy: 'Rohan Mehta',
    createdAt: '2026-09-15T11:15:00Z',
    category: 'Enterprise Software & Licenses',
    documents: [
      {
        id: 'doc-41',
        name: 'GST_PrimeLogix.pdf',
        type: 'GST_CERTIFICATE',
        url: '#',
        fileSize: '1.1 MB',
        uploadedAt: '2026-09-15T11:15:00Z',
        verified: true,
      },
      {
        id: 'doc-42',
        name: 'PAN_PrimeLogix.pdf',
        type: 'PAN',
        url: '#',
        fileSize: '480 KB',
        uploadedAt: '2026-09-15T11:15:00Z',
        verified: true,
      },
    ],
    performance: {
      deliveryPerformance: 95,
      qualityRating: 4.7,
      priceCompetitiveness: 4.2,
      responseRate: 96,
      overallRating: 4.6,
      totalOrdersCompleted: 12,
    },
  },
  {
    id: 'ven-5',
    companyName: 'Nexus Networks & Telecom',
    businessType: 'Private Limited',
    contactPerson: 'Manoj Kapoor',
    email: 'manoj@nexusnetworks.co.in',
    phone: '+91 98190 22334',
    address: 'Unit 5B, Mindspace IT Park, Malad West',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400064',
    gstNumber: '27AABCN1122D1Z4',
    panNumber: 'AABCN1122D',
    bankName: 'Kotak Mahindra Bank',
    bankAccount: '778899001122',
    ifscCode: 'KKBK0000678',
    status: 'REJECTED',
    rejectionReason: 'Invalid GST identification number and expired trade compliance credentials.',
    createdAt: '2026-08-25T15:45:00Z',
    category: 'Networking & Telecommunications',
    documents: [
      {
        id: 'doc-51',
        name: 'Nexus_GST_Doc.pdf',
        type: 'GST_CERTIFICATE',
        url: '#',
        fileSize: '820 KB',
        uploadedAt: '2026-08-25T15:45:00Z',
        verified: false,
      },
    ],
  },
];
